# Generated by Django 4.2.18 on 2025-02-07 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# posts.migrations.0014_auto_20200413_2227
# posts.migrations.0020_migrate_tags
# posts.migrations.0023_post_feeditem
# posts.migrations.0024_migrate_tags

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syndications', '0001_squashed_0016_data_migration'),
        ('profiles', '0001_squashed_0002_profile_twitter_screenname'),
        ('contenttypes', '__first__'),
        ('pages', '0001_squashed_0005_profile_short_bio'),
        ('feed', '0001_squashed_0012_feeditem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('summary', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.category')),
                ('tags', models.ManyToManyField(related_name='posts', to='posts.tag')),
                ('is_published', models.BooleanField(default=False)),
                ('syndicated_to_twitter', models.DateTimeField(null=True)),
                ('syndicate_to_twitter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterSyndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_syndication', to='posts.post')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_str', models.TextField(default=123, max_length=40)),
                ('screen_name', models.CharField(default='BrentLineberry', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TwitterSyndication',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='long_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='short_content',
        ),
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.CharField(max_length=280),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='old_tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts_post_related', related_query_name='posts_posts', to='feed.tag'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='old_tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='feeditem',
            field=models.OneToOneField(auto_created=True, db_column='feeditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='post', to='feed.feeditem'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='feeditem',
            field=models.OneToOneField(auto_created=True, db_column='feeditem_ptr', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='post', serialize=False, to='feed.feeditem'),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='feeditem',
            new_name='feeditem_ptr',
        ),
        migrations.AlterField(
            model_name='post',
            name='feeditem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem'),
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='old_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='old_is_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='old_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='old_updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='old_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='old_is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='old_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='old_updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='long_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='short_content',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='post',
            name='syndicate_to_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='syndicated_to_mastodon',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='HTML supported.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(help_text='Markdown supported.', max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.category'),
        ),
    ]
