# Generated by Django 5.2.5 on 2025-08-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('posts', '0001_squashed_0034_alter_post_category'), ('posts', '0035_rename_content_post_content_md_and_more'), ('posts', '0036_alter_post_content_md_alter_post_summary_md_and_more'), ('posts', '0037_remove_post_syndicate_to_twitter_and_more')]

    initial = True

    dependencies = [
        ('contenttypes', '__first__'),
        ('feed', '0001_squashed_0012_feeditem_created'),
        ('pages', '0001_squashed_0005_profile_short_bio'),
        ('profiles', '0001_squashed_0002_profile_twitter_screenname'),
        ('syndications', '0001_squashed_0016_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title_md', models.TextField(help_text='Markdown supported.')),
                ('summary_md', models.TextField(help_text='Markdown supported.')),
                ('content_md', models.TextField(help_text='Markdown supported.')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.category')),
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
            ],
        ),
    ]
