# Generated by Django 5.2.13 on 2026-04-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('posts', '0001_squashed_0037_remove_post_syndicate_to_twitter_and_more'), ('posts', '0038_auto_20250829_2058'), ('posts', '0039_remove_post_syndicate_to_mastodon_and_more'), ('posts', '0040_auto_20260111_1851'), ('posts', '0041_rename_content_md_post_old_content_md'), ('posts', '0042_remove_post_old_content_md'), ('posts', '0043_auto_20260211_2054'), ('posts', '0044_rename_summary_md_post_old_summary_md'), ('posts', '0045_remove_post_old_summary_md'), ('posts', '0046_auto_20260218_2023'), ('posts', '0047_rename_title_md_post_old_title_md'), ('posts', '0048_remove_post_old_title_md'), ('posts', '0049_remove_post_category'), ('posts', '0050_auto_20260309_0954'), ('posts', '0051_rename_slug_post_old_slug'), ('posts', '0052_remove_post_old_slug'), ('posts', '0053_auto_20260331_1921'), ('posts', '0054_delete_category_delete_post')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
