# Generated by Django 3.0.4 on 2020-03-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_squashed_0002_profile_twitter_screenname'),
        ('posts', '0002_auto_20200312_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile'),
        ),
    ]
