# Generated by Django 3.0.4 on 2020-03-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_squashed_0002_profile_twitter_screenname'),
        ('posts', '0005_auto_20200317_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile'),
        ),
    ]
