# Generated by Django 3.0.4 on 2020-03-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200318_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='syndicated_to_twitter',
            field=models.DateTimeField(null=True),
        ),
    ]
