# Generated by Django 3.0.4 on 2020-04-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_syndicated_to_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='syndicate_to_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TwitterSyndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('url', models.TextField(max_length=2000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
