# Generated by Django 3.0.4 on 2020-04-01 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200401_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittersyndication',
            name='name',
        ),
        migrations.RemoveField(
            model_name='twittersyndication',
            name='url',
        ),
        migrations.AddField(
            model_name='twittersyndication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twittersyndication',
            name='id_str',
            field=models.TextField(default=123, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twittersyndication',
            name='screen_name',
            field=models.CharField(default='BrentLineberry', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twittersyndication',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_syndication', to='posts.Post'),
        ),
    ]
