# Generated by Django 3.0.4 on 2020-04-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200413_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterSyndication',
        ),
    ]
