# Generated by Django 3.0.4 on 2020-04-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('posts', '0017_auto_20200414_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_tags',
            field=models.ManyToManyField(related_name='posts', to='feed.Tag'),
        ),
    ]
