# Generated by Django 3.0.4 on 2020-04-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200414_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='old_tags',
        ),
    ]
