# Generated by Django 3.0.4 on 2020-04-17 01:10

from django.db import migrations

def migrate_data(apps, schema_editor):
    NewTag = apps.get_model('feed','Tag')
    OldTag = apps.get_model('posts','Tag')

    for tag in OldTag.objects.all():
        new_tags = NewTag.objects.filter(slug=tag.slug)

        new_tag = NewTag(name=tag.name, slug=tag.slug)

        if new_tags.exists():
            new_tag = new_tags[0]
        else:
            new_tag.save()

        new_tag.posts_post_related.add(*tag.posts.all())
        new_tag.save()

def unmigrate_data(apps, schema_editor):
    NewTag = apps.get_model('feed','Tag')
    OldTag = apps.get_model('posts','Tag')

    for tag in NewTag.objects.all():
        old_tags = OldTag.objects.filter(slug=tag.slug)

        old_tag = OldTag(name=tag.name, slug=tag.slug)

        if old_tags.exists():
            old_tag = old_tags[0]
        else:
            old_tag.save()

        old_tag.posts.add(*tag.posts_post_related.all())
        old_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_tags'),
    ]

    operations = [
        migrations.RunPython(migrate_data, unmigrate_data),
    ]
