# Generated by Django 3.0.4 on 2020-04-18 01:45

from django.db import migrations, models
import django.db.models.deletion

def up(apps,schema_editor):
    Post = apps.get_model('posts','Post')
    FeedItem = apps.get_model('feed', 'FeedItem')

    for post in Post.objects.all():
        feeditem = FeedItem()
        feeditem.save()
        post.feeditem = feeditem
        post.save()

def down(apps,schema_editor):
    Post = apps.get_model('posts','Post')

    for post in Post.objects.all():
        post.feeditem.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_squashed_0003_feeditem_tags'),
        ('posts', '0022_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feeditem',
            field=models.OneToOneField(auto_created=True, db_column='feeditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='post', to='feed.FeedItem'),
        ),
        migrations.RunPython(up,down)
    ]
