# Generated by Django 3.0.4 on 2020-04-18 02:13

from django.db import migrations

def up(apps, schema_editor):
    Post = apps.get_model('posts','Post')

    for post in Post.objects.all():
        post.feeditem.tags.set(post.tags.all())
        post.save()

def down(apps, schema_editor):
    Post = apps.get_model('posts','Post')

    for post in Post.objects.all():
        post.tags.set(post.feeditem.tags.all())
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_feeditem'),
        ('feed', '0001_squashed_0003_feeditem_tags'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
