# Generated by Django 3.0.4 on 2020-04-18 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feeditem_tags'),
        ('posts', '0025_remove_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='feeditem',
            field=models.OneToOneField(auto_created=True, db_column='feeditem_ptr', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='post', serialize=False, to='feed.FeedItem'),
        ),
    ]
