# Generated by Django 3.0.4 on 2020-04-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20200417_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feeditem',
            new_name='feeditem_ptr',
        ),
    ]
