# Generated by Django 3.0.4 on 2020-04-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20200418_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='long_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='short_content',
            new_name='summary',
        ),
    ]
