# Generated by Django 4.1.3 on 2022-12-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20200422_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='syndicate_to_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='syndicated_to_mastodon',
            field=models.DateTimeField(null=True),
        ),
    ]
