# Generated by Django 4.1.6 on 2023-05-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_post_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='HTML supported.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(help_text='Markdown supported.', max_length=280),
        ),
    ]
