# Generated by Django 4.2.18 on 2025-08-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_squashed_0034_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_md',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='summary_md',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_md',
        ),
    ]
