# Generated by Django 4.2.18 on 2025-08-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_rename_content_post_content_md_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_md',
            field=models.TextField(help_text='Markdown supported.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_md',
            field=models.TextField(help_text='Markdown supported.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_md',
            field=models.TextField(help_text='Markdown supported.'),
        ),
    ]
