# Generated by Django 4.2.18 on 2025-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_post_content_md_alter_post_summary_md_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='syndicate_to_twitter',
        ),
        migrations.RemoveField(
            model_name='post',
            name='syndicated_to_twitter',
        ),
    ]
