# Generated by Django 5.2.5 on 2025-12-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20250829_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='syndicate_to_mastodon',
        ),
        migrations.RemoveField(
            model_name='post',
            name='syndicated_to_mastodon',
        ),
    ]
