# Generated by Django 5.2.5 on 2026-01-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_auto_20260111_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_md',
            new_name='old_content_md',
        ),
    ]
