# Generated by Django 5.2.5 on 2026-01-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_rename_content_md_post_old_content_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='old_content_md',
        ),
    ]
