# Generated by Django 5.2.11 on 2026-02-12 01:54

from django.db import migrations

def up(apps, schema_editor):
    app_label = "posts"
    model_str = "Post"

    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.new_summary_md = item.summary_md

        feed_item.save()


def down(apps, schema_editor):
    app_label = "posts"
    model_str = "Post"

    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        item.summary_md = feed_item.new_summary_md

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_remove_post_old_content_md'),
        ('feed', '0019_feeditem_new_summary_md')
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
