# Generated by Django 5.2.11 on 2026-02-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_auto_20260211_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary_md',
            new_name='old_summary_md',
        ),
    ]
