# Generated by Django 5.2.11 on 2026-02-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_rename_summary_md_post_old_summary_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='old_summary_md',
        ),
    ]
