# Generated by Django 5.2.11 on 2026-02-19 01:23

from django.db import migrations

app_label = "posts"
model_str = "Post"

feed_item_app_label = "feed"
feed_item_model_str = "FeedItem"

def up(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.new_title_md = item.title_md

        feed_item.save()


def down(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        item.title_md = feed_item.new_title_md

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_remove_post_old_summary_md'),
        ('feed', '0023_feeditem_new_title_md'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
