# Generated by Django 5.2.11 on 2026-02-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_auto_20260218_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_md',
            new_name='old_title_md',
        ),
    ]
