# Generated by Django 5.2.11 on 2026-02-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_rename_title_md_post_old_title_md'),
        ('feed', '0024_rename_new_title_md_feeditem_title_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='old_title_md',
        ),
    ]
