# Generated by Django 5.2.11 on 2026-03-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_remove_post_old_title_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
