# Generated by Django 5.2.11 on 2026-03-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_auto_20260309_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='old_slug',
        ),
    ]
