# Generated by Django 5.2.11 on 2026-03-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_rename_slug_post_old_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='old_slug',
        ),
    ]
