# Generated by Django 5.2.11 on 2026-03-31 23:21

from django.db import migrations

app_label = "posts"
model_str = "Post"

def up(apps, schema_editor):
    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)
    FeedImage = apps.get_model(feed_item_app_label, "Image")

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.post_type = 'ARTICLE'
        feed_item.save()


def down(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_remove_post_old_slug'),
        ('feed', '0033_feeditem_post_type' ),
    ]

    operations = [
        
    ]
