# Generated by Django 5.2.11 on 2026-04-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_auto_20260331_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
