# Generated by Django 5.2.5 on 2025-08-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_squashed_0012_feeditem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('url', models.URLField(max_length=2048)),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
                ('quote_md', models.TextField(blank=True, help_text='CommonMark supported.', verbose_name='quote')),
                ('title_md', models.TextField(blank=True, help_text='Markdown supported. Inline elements only.', verbose_name='title')),
                ('commentary_md', models.TextField(blank=True, help_text='Markdown supported.', verbose_name='commentary')),
                ('commonmark_rendered_at', models.DateTimeField(null=True)),
            ],
            bases=('feed.feeditem',),
        ),
    ]
