# Generated by Django 4.1.3 on 2023-01-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0004_auto_20200417_2246_squashed_0009_alter_feeditem_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('url', models.CharField(blank=True, max_length=2000, null=True)),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('commentary', models.CharField(blank=True, max_length=280)),
                ('quote', models.CharField(blank=True, max_length=280)),
            ],
            bases=('feed.feeditem',),
        ),
    ]
