# Generated by Django 4.1.3 on 2023-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='syndicate_to_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='syndicate_to_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='syndicated_to_mastodon',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='syndicated_to_twitter',
            field=models.DateTimeField(null=True),
        ),
    ]
