# Generated by Django 4.1.3 on 2023-01-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
