# Generated by Django 4.1.3 on 2023-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_alter_bookmark_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='commentary',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
