# Generated by Django 4.1.3 on 2023-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_alter_bookmark_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='commentary',
            field=models.CharField(blank=True, default='', max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
