# Generated by Django 4.2.18 on 2025-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_squashed_0006_alter_bookmark_commentary_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='commentary',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
