# Generated by Django 4.2.18 on 2025-02-07 14:37

from django.db import migrations, models
import feed.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_squashed_0006_alter_bookmark_commentary_alter_bookmark_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='commentary',
            new_name='commentary_txt'
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='quote',
            new_name='quote_txt'
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='title',
            new_name='title_txt'
        ),
        migrations.AddField(
            model_name='bookmark',
            name='commentary_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='quote_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='quote_md',
            field=feed.fields.CommonmarkField(blank=True, help_text='CommonMark supported.', html_field='quote_html', txt_field='quote_txt', verbose_name='quote'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='title_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='title_md',
            field=feed.fields.CommonmarkInlineField(blank=True, help_text='CommonMark supported. Inline elements only.', html_field='title_html', txt_field='title_txt', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='commentary_md',
            field=feed.fields.CommonmarkField(blank=True, help_text='CommonMark supported.', html_field='commentary_html', txt_field='commentary_txt', verbose_name='commentary'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='commentary_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='quote_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title_txt',
            field=models.TextField(blank=True),
        ),
    ]
