# Generated by Django 4.2.18 on 2025-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_alter_bookmark_commentary_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='commentary',
            field=models.CharField(blank=True, db_column='commentary_plain', max_length=280),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='quote',
            field=models.CharField(blank=True, db_column='quote_plain', max_length=280),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, db_column='title_plain', max_length=100),
        ),
    ]
