# Generated by Django 4.2.18 on 2025-02-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_alter_bookmark_commentary_alter_bookmark_quote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='commentary',
            new_name='commentary_txt',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='quote',
            new_name='quote_txt',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='title',
            new_name='title_txt',
        ),
    ]
