# Generated by Django 4.2.18 on 2025-02-06 21:40

from django.db import migrations
import feed.fields



class Migration(migrations.Migration):
    dependencies = [
        ('bookmarks', '0007_remove_bookmark_commentary_remove_bookmark_quote_and_more'),
    ]

    operations = []
