# Generated by Django 4.2.18 on 2025-02-06 21:40

from django.db import migrations
import feed.fields

def forwards_func(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    db_alias = schema_editor.connection.alias

    for bookmark in Bookmark.objects.using(db_alias).all():
        bookmark.commentary_md = bookmark.commentary_txt
        bookmark.quote_md = bookmark.quote_txt
        bookmark.title_md = bookmark.title_txt
        bookmark.save()

def reverse_func(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    db_alias = schema_editor.connection.alias

    for bookmark in Bookmark.objects.using(db_alias).all():
        bookmark.commentary_md = ""
        bookmark.quote_md = ""
        bookmark.title_md = ""
        bookmark.commentary_html = ""
        bookmark.quote_html = ""
        bookmark.title_html = ""
        bookmark.save()

class Migration(migrations.Migration):
    dependencies = [
        ('bookmarks', '0007_remove_bookmark_commentary_remove_bookmark_quote_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
