# Generated by Django 4.2.18 on 2025-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0008_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='commonmark_rendered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
