# Generated by Django 4.2.18 on 2025-02-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0009_bookmark_commonmark_rendered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
