# Generated by Django 4.2.18 on 2025-02-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0009_alter_bookmark_commentary_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='commentary_txt',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='quote_txt',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
