# Generated by Django 4.2.18 on 2025-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0010_alter_bookmark_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='commentary_html',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='commentary_txt',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='quote_html',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='quote_txt',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='title_html',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='title_txt',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='commentary_md',
            field=models.TextField(blank=True, help_text='Markdown supported.', verbose_name='commentary'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='quote_md',
            field=models.TextField(blank=True, help_text='CommonMark supported.', verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Inline elements only.', verbose_name='title'),
        ),
    ]
