# Generated by Django 4.2.18 on 2025-02-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0010_alter_bookmark_commentary_txt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='commentary_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='quote_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='title_md',
            field=models.TextField(blank=True),
        ),
    ]
