# Generated by Django 4.2.18 on 2025-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0011_remove_bookmark_commentary_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='syndicate_to_twitter',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='syndicated_to_twitter',
        ),
    ]
