# Generated by Django 5.2.5 on 2025-12-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0013_auto_20250829_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='syndicate_to_mastodon',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='syndicated_to_mastodon',
        ),
    ]
