# Generated by Django 4.2.18 on 2025-02-06 21:40

from django.db import migrations
import feed.fields

def forwards_func(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    db_alias = schema_editor.connection.alias

    for bookmark in Bookmark.objects.using(db_alias).all():
        bookmark.save()

def reverse_func(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    db_alias = schema_editor.connection.alias

    for bookmark in Bookmark.objects.all():
        print(bookmark)

class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0013_bookmark_commentary_html_bookmark_quote_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='commentary_md',
            field=feed.fields.CommonmarkField(blank=True, help_text='CommonMark supported.', html_field='commentary_html', txt_field='commentary_txt', verbose_name='commentary'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='quote_md',
            field=feed.fields.CommonmarkField(blank=True, help_text='CommonMark supported.', html_field='quote_html', txt_field='quote_txt', verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title_md',
            field=feed.fields.CommonmarkInlineField(blank=True, help_text='CommonMark supported. Inline elements only.', html_field='title_html', txt_field='title_txt', verbose_name='title'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
