# Generated by Django 5.2.11 on 2026-02-17 01:39

from django.db import migrations

app_label = "bookmarks"
model_str = "Bookmark"

feed_item_app_label = "feed"
feed_item_model_str = "FeedItem"

def up(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.content_md = item.commentary_md

        feed_item.save()


def down(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        item.commentary_md = feed_item.content_md

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0014_remove_bookmark_syndicate_to_mastodon_and_more'),
        ('feed', '0018_rename_new_content_md_feeditem_content_md'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
