# Generated by Django 5.2.11 on 2026-02-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0015_auto_20260216_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='commentary_md',
        ),
    ]
