# Generated by Django 5.2.11 on 2026-02-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0017_auto_20260217_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='quote_md',
            new_name='old_quote_md',
        ),
    ]
