# Generated by Django 5.2.11 on 2026-02-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0018_rename_quote_md_bookmark_old_quote_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='old_quote_md',
        ),
    ]
