# Generated by Django 5.2.11 on 2026-02-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0020_auto_20260218_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='title_md',
            new_name='old_title_md',
        ),
    ]
