# Generated by Django 5.2.11 on 2026-02-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0022_remove_bookmark_old_title_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
