# Generated by Django 5.2.11 on 2026-03-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0026_remove_bookmark_old_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='commonmark_rendered_at',
        ),
    ]
