# Generated by Django 5.2.11 on 2026-03-09 17:11

from django.db import migrations

app_label = "bookmarks"
model_str = "Bookmark"

feed_item_app_label = "feed"
feed_item_model_str = "FeedItem"

def up(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.post_type = 'BOOKMARK'

        feed_item.save()


def down(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0027_remove_bookmark_commonmark_rendered_at'),
        ('feed', '0033_feeditem_post_type'),
    ]

    operations = [
        
    ]
