# Generated by Django 5.2.13 on 2026-04-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0028_auto_20260309_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
