# Generated by Django 3.0.4 on 2020-03-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=2000)),
                ('url_display', models.CharField(max_length=80, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('is_owner', models.BooleanField(default=False)),
                ('short_bio', models.CharField(max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=2000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
