# Generated by Django 3.0.4 on 2020-04-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_screenname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
