# Generated by Django 4.2.18 on 2025-08-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitter_screenname',
        ),
    ]
