# Generated by Django 5.2.13 on 2026-05-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_squashed_0004_remove_profile_twitter_screenname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('content', models.CharField(max_length=280)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='profiles.profile')),
            ],
        ),
    ]
