# Generated by Django 5.2.14 on 2026-06-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_metatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='given_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
