# Generated by Django 4.2.18 on 2025-02-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_squashed_0012_feeditem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('source_author_name', models.CharField(default='Anonymous', max_length=200)),
                ('source_author_url', models.URLField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('feed.feeditem', models.Model),
        ),
    ]
