# Generated by Django 5.2.13 on 2026-04-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('reposts', '0001_squashed_0004_remove_repost_source_published'), ('reposts', '0005_auto_20250829_2106'), ('reposts', '0006_remove_repost_syndicate_to_mastodon_and_more'), ('reposts', '0007_alter_repost_url'), ('reposts', '0008_auto_20260219_2055'), ('reposts', '0009_rename_url_repost_old_url'), ('reposts', '0010_remove_repost_old_url'), ('reposts', '0011_auto_20260307_1513'), ('reposts', '0012_auto_20260307_1523'), ('reposts', '0013_rename_source_author_name_repost_old_source_author_name_and_more'), ('reposts', '0014_remove_repost_content_and_more'), ('reposts', '0015_auto_20260331_2045'), ('reposts', '0016_delete_repost')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
