# Generated by Django 4.2.3 on 2023-08-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0002_alter_repost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='source_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='repost',
            name='source_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
