# Generated by Django 5.2.5 on 2025-08-30 01:06

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def up(apps, schema_editor):
    app_label = "reposts"
    model_str = "Repost"

    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)
    MastodonStatus = apps.get_model("syndications", "MastodonStatus")
    content_type = ContentType.objects.get(app_label=app_label, model=model_str.lower())
    feed_item_content_type = ContentType.objects.get(app_label=feed_item_app_label, model=feed_item_model_str.lower())

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.new_syndicated_to_mastodon = item.syndicated_to_mastodon
        feed_item.new_syndicate_to_mastodon = item.syndicate_to_mastodon

        statuses = MastodonStatus.objects.filter(content_type_id=content_type.id, object_id=item.pk)
        for status in statuses:
            status.pk = None
            status.content_type_id=feed_item_content_type.id
            status.object_id = feed_item.id
            status._state.adding = True
            status.save()

        feed_item.save()


def down(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0001_squashed_0004_remove_repost_source_published'),
        ('feed', '0013_feeditem_new_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
