# Generated by Django 5.2.5 on 2025-12-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0005_auto_20250829_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='syndicate_to_mastodon',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='syndicated_to_mastodon',
        ),
    ]
