# Generated by Django 5.2.11 on 2026-02-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0006_remove_repost_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
