# Generated by Django 5.2.11 on 2026-02-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0008_auto_20260219_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repost',
            old_name='url',
            new_name='old_url',
        ),
    ]
