# Generated by Django 5.2.11 on 2026-02-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0009_rename_url_repost_old_url'),
        ('feed', '0026_rename_new_url_feeditem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='old_url',
        ),
    ]
