# Generated by Django 5.2.11 on 2026-03-07 20:13

from django.db import migrations

app_label = "reposts"
model_str = "Repost"

feed_item_app_label = "feed"
feed_item_model_str = "FeedItem"

def up(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.content_md = item.content

        feed_item.save()


def down(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        item.content = feed_item.content_md

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0010_remove_repost_old_url'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
