# Generated by Django 5.2.11 on 2026-03-07 20:23

from django.db import migrations

app_label = "reposts"
model_str = "Repost"

feed_item_app_label = "feed"
feed_item_model_str = "FeedItem"

def up(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.new_source_name = item.source_name
        feed_item.new_source_author_name = item.source_author_name
        feed_item.new_source_author_url = item.source_author_url

        feed_item.save()


def down(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        
        item.source_name = feed_item.new_source_name
        item.source_author_name = feed_item.new_source_author_name
        item.source_author_url = feed_item.new_source_author_url

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0011_auto_20260307_1513'),
        ('feed', '0029_feeditem_new_source_author_name_and_more'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
