# Generated by Django 5.2.11 on 2026-03-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0012_auto_20260307_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repost',
            old_name='source_author_name',
            new_name='old_source_author_name',
        ),
        migrations.RenameField(
            model_name='repost',
            old_name='source_author_url',
            new_name='old_source_author_url',
        ),
        migrations.RenameField(
            model_name='repost',
            old_name='source_name',
            new_name='old_source_name',
        ),
    ]
