# Generated by Django 5.2.11 on 2026-03-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0013_rename_source_author_name_repost_old_source_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='old_source_author_name',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='old_source_author_url',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='old_source_name',
        ),
    ]
