# Generated by Django 5.2.11 on 2026-04-01 00:45

from django.db import migrations

app_label = "reposts"
model_str = "Repost"

def up(apps, schema_editor):
    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.post_type = 'REPOST'
        feed_item.save()

def down(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0014_remove_repost_content_and_more'),
        ('feed', '0033_feeditem_post_type' ),
    ]

    operations = [
        
    ]
