# Generated by Django 5.2.13 on 2026-04-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposts', '0015_auto_20260331_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
