# Generated by Django 4.1.3 on 2022-12-10 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0001_mastodonstatus_content_type_mastodonstatus_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonstatus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
