# Generated by Django 3.0.4 on 2020-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0002_auto_20200421_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='full_text',
            field=models.TextField(max_length=560, null=True),
        ),
    ]
