# Generated by Django 4.2.3 on 2023-07-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0002_mastodonstatus_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
