# Generated by Django 4.2.3 on 2023-08-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0003_alter_tweet_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('reply_to_url', models.URLField()),
                ('content', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_url', models.URLField(blank=True, null=True)),
                ('author_photo', models.URLField(blank=True, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MastodonReply',
            fields=[
                ('reply_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syndications.reply')),
                ('id_str', models.CharField(max_length=40)),
                ('in_reply_to_id_str', models.CharField(max_length=40)),
            ],
            bases=('syndications.reply',),
        ),
        migrations.AddConstraint(
            model_name='mastodonreply',
            constraint=models.UniqueConstraint(fields=('id_str',), name='unique_mastodon_id'),
        ),
    ]
