# Generated by Django 3.0.4 on 2020-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0003_tweet_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id_str',
            field=models.CharField(max_length=40),
        ),
    ]
