# Generated by Django 3.0.4 on 2020-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0004_auto_20200424_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='id_str',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='screen_name',
            field=models.CharField(max_length=30),
        ),
    ]
