# Generated by Django 4.2.3 on 2023-08-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0004_reply_mastodonreply_mastodonreply_unique_mastodon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
