# Generated by Django 3.0.4 on 2020-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0005_auto_20200428_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_screen_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_status_id_str',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
