# Generated by Django 3.0.4 on 2020-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0006_auto_20200501_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField()),
                ('athlete', models.IntegerField()),
                ('distance', models.FloatField()),
                ('moving_time', models.IntegerField()),
                ('elapsed_time', models.IntegerField()),
                ('total_elevation_gain', models.FloatField()),
                ('type', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('private', models.BooleanField()),
            ],
        ),
    ]
