# Generated by Django 4.2.3 on 2023-08-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0006_repost_mastodonboost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_of_url', models.URLField()),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_url', models.URLField(blank=True, null=True)),
                ('author_photo', models.URLField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MastodonFavourite',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syndications.like')),
                ('account_id_str', models.CharField(max_length=40)),
                ('favourite_of_id_str', models.CharField(max_length=40)),
            ],
            bases=('syndications.like',),
        ),
        migrations.AddConstraint(
            model_name='mastodonfavourite',
            constraint=models.UniqueConstraint(fields=('account_id_str', 'favourite_of_id_str'), name='unique_mastodon_account_id_str_favourite_of_id_str'),
        ),
    ]
