# Generated by Django 4.2.3 on 2023-08-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0007_like_mastodonfavourite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
