# Generated by Django 3.0.4 on 2020-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0007_stravaactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
