# Generated by Django 4.2.3 on 2023-08-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0008_like_updated_at_reply_updated_at_repost_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonStatusesToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=40)),
                ('result', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='mastodonstatusestoprocess',
            constraint=models.UniqueConstraint(fields=('id_str',), name='unique_mastodon_id_str'),
        ),
    ]
