# Generated by Django 3.0.4 on 2020-05-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0008_stravaactivity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravaactivity',
            name='description',
        ),
    ]
