# Generated by Django 3.0.4 on 2020-05-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('syndications', '0009_remove_stravaactivity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='content_type',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='object_id',
            field=models.PositiveIntegerField(default=24559),
            preserve_default=False,
        ),
    ]
