# Generated by Django 3.0.7 on 2020-06-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0010_auto_20200508_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_token', models.CharField(max_length=32)),
                ('subscription_id', models.IntegerField(null=True)),
            ],
        ),
    ]
