# Generated by Django 4.2.3 on 2023-08-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0011_mastodonpushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastodonpushsubscription',
            name='id',
        ),
        migrations.AddField(
            model_name='mastodonpushsubscription',
            name='singleton',
            field=models.CharField(default='X', max_length=1, primary_key=True, serialize=False),
        ),
    ]
