# Generated by Django 4.1.3 on 2022-12-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0012_stravawebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
    ]
