# Generated by Django 4.2.18 on 2025-01-27 00:19

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0014_rename_mastodonnotification_mastodonpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syndication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='mastodonstatus',
            name='syndication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='syndications.syndication'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='syndication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='syndications.syndication'),
        ),
    ]
