# Generated by Django 4.2.18 on 2025-02-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('syndications', '0001_squashed_0016_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonstatus',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mastodonstatus',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
