# Generated by Django 4.2.18 on 2025-08-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0017_alter_mastodonstatus_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
