# Generated by Django 5.2.5 on 2025-12-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_feeditem_new_syndicate_to_mastodon_and_more'),
        ('syndications', '0001_squashed_0018_delete_tweet_delete_twitteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastodonstatus',
            name='feed_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feeditem'),
        ),
    ]
