# Generated by Django 5.2.13 on 2026-05-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0001_squashed_0019_mastodonstatus_feed_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastodonstatus',
            name='feed_item',
        ),
    ]
