# Generated by Django 4.2.18 on 2025-02-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pages', '0001_initial'), ('pages', '0002_auto_20200309_2101'), ('pages', '0003_profile_isowner'), ('pages', '0004_auto_20200309_2115'), ('pages', '0005_profile_short_bio')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=2000)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('url_display', models.CharField(max_length=80, null=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('short_bio', models.CharField(max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=2000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.profile')),
            ],
        ),
    ]
