# Generated by Django 3.0.4 on 2020-03-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200309_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
