# Generated by Django 3.0.4 on 2020-03-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_profile_isowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isOwner',
            new_name='is_owner',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='urlDisplay',
            new_name='url_display',
        ),
    ]
