# Generated by Django 3.0.4 on 2020-03-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200309_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
