# Generated by Django 5.2.5 on 2025-12-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20250829_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='syndicate_to_mastodon',
        ),
        migrations.RemoveField(
            model_name='like',
            name='syndicated_to_mastodon',
        ),
    ]
