# Generated by Django 5.2.11 on 2026-02-20 01:54

from django.db import migrations

app_label = "likes"
model_str = "Like"

feed_item_app_label = "feed"
feed_item_model_str = "FeedItem"

def up(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.new_url = item.url

        feed_item.save()


def down(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        item.url = feed_item.new_url

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_like_url'),
        ('feed', '0025_feeditem_new_url'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
