# Generated by Django 5.2.11 on 2026-02-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0006_auto_20260219_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='url',
            new_name='old_url',
        ),
    ]
