# Generated by Django 5.2.11 on 2026-03-11 01:27

from django.db import migrations

app_label = "likes"
model_str = "Like"

feed_item_app_label = "feed"
feed_item_model_str = "FeedItem"

def up(apps, schema_editor):
    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.post_type = 'LIKE'

        feed_item.save()


def down(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0008_remove_like_old_url'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
