# Generated by Django 5.2.13 on 2026-04-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0009_auto_20260310_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
