# Generated by Django 4.1.3 on 2023-01-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0004_auto_20200417_2246_squashed_0009_alter_feeditem_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('syndicated_to_twitter', models.DateTimeField(null=True)),
                ('syndicate_to_twitter', models.BooleanField(default=False)),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('content', models.ImageField(upload_to='')),
                ('caption', models.TextField()),
                ('alternative_text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('feed.feeditem', models.Model),
        ),
    ]
