# Generated by Django 4.2.18 on 2025-02-07 14:09

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import photos.models
import photos.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_squashed_0012_feeditem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('syndicated_to_twitter', models.DateTimeField(null=True)),
                ('syndicate_to_twitter', models.BooleanField(default=False)),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, height_field='image_height', keep_meta=False, quality=70, scale=None, size=[1188, 1188], storage=photos.storage.PublicAzureStorage, upload_to=photos.models.upload_to_callable, width_field='image_width')),
                ('caption', models.CharField(blank=True, help_text='Markdown supported.', max_length=560)),
                ('alternative_text', models.CharField(max_length=255)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('image_width', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('feed.feeditem', models.Model),
        ),
    ]
