# Generated by Django 5.2.5 on 2025-08-21 18:42

import django.db.models.deletion
import django_resized.forms
import photos.models
import photos.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_squashed_0012_feeditem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, height_field='image_height', keep_meta=False, quality=70, scale=None, size=[1188, 1188], storage=photos.storage.PublicAzureStorage, upload_to=photos.models.upload_to_callable, width_field='image_width')),
                ('caption_md', models.TextField(blank=True, help_text='Markdown supported.')),
                ('alternative_text', models.CharField(blank=True, max_length=255)),
                ('image_height', models.PositiveIntegerField()),
                ('image_width', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('feed.feeditem', models.Model),
        ),
    ]
