# Generated by Django 4.1.6 on 2023-05-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_caption_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, help_text='Markdown supported.', max_length=560),
        ),
    ]
