# Generated by Django 4.2.17 on 2025-01-09 22:36

from django.db import migrations
import django_resized.forms
import photos.models
import photos.storage


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, height_field='image_height', keep_meta=False, quality=70, scale=None, size=[1188, 1188], storage=photos.storage.PublicAzureStorage, upload_to=photos.models.upload_to_callable, width_field='image_width'),
        ),
    ]
