# Generated by Django 4.2.18 on 2025-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_squashed_0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_width',
            field=models.PositiveIntegerField(),
        ),
    ]
