# Generated by Django 4.2.18 on 2025-08-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_image_height_alter_photo_image_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='caption',
            new_name='caption_md',
        ),
    ]
