# Generated by Django 4.2.18 on 2025-08-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_photo_caption_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
