# Generated by Django 4.2.18 on 2025-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_alter_photo_alternative_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='syndicate_to_twitter',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='syndicated_to_twitter',
        ),
    ]
