# Generated by Django 5.2.5 on 2025-08-29 23:44

import photos.models
import photos.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_squashed_0011_remove_photo_syndicate_to_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=photos.models.OGResizedImageField(crop=None, force_format=None, height_field='image_height', keep_meta=False, quality=70, scale=None, size=[1188, 1188], storage=photos.storage.PublicAzureStorage, upload_to=photos.models.upload_to_callable, width_field='image_width'),
        ),
    ]
