# Generated by Django 5.2.5 on 2026-02-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_auto_20260210_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='caption_md',
        ),
    ]
