# Generated by Django 5.2.11 on 2026-03-06 01:39

from django.db import migrations

app_label = "photos"
model_str = "Photo"

def up(apps, schema_editor):
    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)
    FeedImage = apps.get_model(feed_item_app_label, "Image")

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)

        description = item.alternative_text if item.alternative_text != "" else feed_item.content_md

        image = FeedImage(image=item.image, description=description)
        image.save()

        feed_item.postimage_set.create(image=image, alt=item.alternative_text)
        feed_item.save()


def down(apps, schema_editor):
    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        image = feed_item.images.first()

        if image is None:
            continue
        
        item.image = image.image
        item.alternative_text = image.description

        item.save()

        feed_item.images.all().delete()
        feed_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_remove_photo_caption_md'),
        ('feed', '0027_image_postimage_feeditem_images'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
