# Generated by Django 5.2.11 on 2026-03-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20260305_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='alternative_text',
            new_name='old_alternative_text',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='old_image',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image_height',
            new_name='old_image_height',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image_width',
            new_name='old_image_width',
        ),
    ]
