# Generated by Django 5.2.11 on 2026-03-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_rename_alternative_text_photo_old_alternative_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='old_alternative_text',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='old_image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='old_image_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='old_image_width',
        ),
    ]
