# Generated by Django 5.2.11 on 2026-03-14 20:49

from django.db import migrations

app_label = "photos"
model_str = "Photo"

def up(apps, schema_editor):
    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)
    FeedImage = apps.get_model(feed_item_app_label, "Image")

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.post_type = 'PHOTO'
        feed_item.save()


def down(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_remove_photo_old_alternative_text_and_more'),
        ('feed', '0033_feeditem_post_type' ),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
