# Generated by Django 5.2.13 on 2026-04-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_auto_20260314_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
