# Generated by Django 4.2.18 on 2025-02-07 14:07

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# notes.migrations.0006_note_feeditem_ptr
# notes.migrations.0007_migrate_tags

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_squashed_0012_feeditem_created'),
        ('profiles', '0001_squashed_0002_profile_twitter_screenname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndicated_to_twitter', models.DateTimeField(null=True)),
                ('syndicate_to_twitter', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(null=True)),
                ('short_content', models.CharField(max_length=280)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
                ('tags', models.ManyToManyField(related_name='notes_note_related', related_query_name='notes_notes', to='feed.tag')),
                ('feeditem_ptr', models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='feed.feeditem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AlterField(
            model_name='note',
            name='feeditem_ptr',
            field=models.OneToOneField(auto_created=True, db_column='feeditem_ptr', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='feed.feeditem'),
        ),
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='feeditem_ptr',
            field=models.OneToOneField(auto_created=True, db_column='feeditem_ptr', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem'),
        ),
        migrations.AlterField(
            model_name='note',
            name='feeditem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem'),
        ),
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='old_author',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='is_published',
            new_name='old_is_published',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='published',
            new_name='old_published',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated',
            new_name='old_updated',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_author',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_is_published',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_published',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_updated',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='short_content',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=560),
        ),
        migrations.AddField(
            model_name='note',
            name='syndicate_to_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='syndicated_to_mastodon',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(help_text='Markdown supported.', max_length=560),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='Markdown'),
        ),
    ]
