# Generated by Django 5.2.5 on 2025-08-21 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_squashed_0012_feeditem_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('content_md', models.TextField(help_text='Markdown supported.')),
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
