# Generated by Django 3.0.4 on 2020-04-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_squashed_0003_feeditem_tags'),
        ('notes', '0002_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes_note_related', related_query_name='notes_notes', to='feed.Tag'),
        ),
    ]
