# Generated by Django 3.0.4 on 2020-04-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_feeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='feeditem',
        ),
    ]
