# Generated by Django 3.0.4 on 2020-04-18 02:24

from django.db import migrations, models
import django.db.models.deletion

def up(apps,schema_editor):
    Note = apps.get_model('notes','Note')
    FeedItem = apps.get_model('feed', 'FeedItem')

    for note in Note.objects.all():
        feeditem = FeedItem()
        feeditem.save()
        note.feeditem = feeditem
        note.save()

def down(apps,schema_editor):
    Note = apps.get_model('notes','Note')

    for note in Note.objects.all():
        note.feeditem.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feeditem_tags'),
        ('notes', '0005_remove_note_feeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='feeditem_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='feed.FeedItem'),
        ),
        migrations.RunPython(up,down)
    ]
