# Generated by Django 3.0.4 on 2020-04-18 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feeditem_tags'),
        ('notes', '0009_auto_20200417_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='feeditem_ptr',
            field=models.OneToOneField(auto_created=True, db_column='feeditem_ptr', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.FeedItem'),
        ),
    ]
