# Generated by Django 3.0.4 on 2020-04-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20200417_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='old_author',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_is_published',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_published',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_updated',
        ),
    ]
