# Generated by Django 3.0.4 on 2020-04-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20200418_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='short_content',
            new_name='content',
        ),
    ]
