# Generated by Django 4.1.3 on 2022-12-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20200421_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='syndicate_to_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='syndicated_to_mastodon',
            field=models.DateTimeField(null=True),
        ),
    ]
