# Generated by Django 4.1.6 on 2023-05-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_note_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(help_text='Markdown supported.', max_length=560),
        ),
    ]
