# Generated by Django 4.2.17 on 2025-01-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='Markdown'),
        ),
    ]
