# Generated by Django 4.2.18 on 2025-08-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_squashed_0018_alter_note_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='content_md',
        ),
    ]
