# Generated by Django 4.2.18 on 2025-08-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_rename_content_note_content_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_md',
            field=models.TextField(help_text='Markdown supported.'),
        ),
    ]
