# Generated by Django 4.2.18 on 2025-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_alter_note_content_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='syndicate_to_twitter',
        ),
        migrations.RemoveField(
            model_name='note',
            name='syndicated_to_twitter',
        ),
    ]
