# Generated by Django 5.2.5 on 2025-08-30 00:44

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def up(apps, schema_editor):
    app_label = "notes"
    model_str = "Note"

    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)
    MastodonStatus = apps.get_model("syndications", "MastodonStatus")
    content_type = ContentType.objects.get(app_label=app_label, model=model_str.lower())

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.new_syndicated_to_mastodon = item.syndicated_to_mastodon
        feed_item.new_syndicate_to_mastodon = item.syndicate_to_mastodon

        statuses = MastodonStatus.objects.filter(content_type_id=content_type.id, object_id=item.pk)
        for status in statuses:
            status.feed_item_id = feed_item.id
            status.save()

        feed_item.save()


def down(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_squashed_0021_remove_note_syndicate_to_twitter_and_more'),
        ('feed', '0013_feeditem_new_syndicate_to_mastodon_and_more'),
        ('syndications','0019_mastodonstatus_feed_item'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
