# Generated by Django 5.2.5 on 2026-01-11 21:29

from django.db import migrations

def up(apps, schema_editor):
    app_label = "notes"
    model_str = "Note"

    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.new_content_md = item.content_md

        feed_item.save()


def down(apps, schema_editor):
    app_label = "notes"
    model_str = "Note"

    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        item.content_md = feed_item.new_content_md

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_feeditem_new_content_md'),
        ('notes', '0023_remove_note_syndicate_to_mastodon_and_more')
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
