# Generated by Django 5.2.5 on 2026-01-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_auto_20260111_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content_md',
            new_name='old_content_md',
        ),
    ]
