# Generated by Django 5.2.5 on 2026-01-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_rename_content_md_note_old_content_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='old_content_md',
        ),
    ]
