# Generated by Django 5.2.11 on 2026-03-14 02:04

from django.db import migrations

app_label = "notes"
model_str = "Note"

def up(apps, schema_editor):
    feed_item_app_label = "feed"
    feed_item_model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)
    FeedItem = apps.get_model(feed_item_app_label, feed_item_model_str)

    for item in model.objects.all():
        feed_item = FeedItem.objects.get(pk=item.pk)
        feed_item.post_type = 'NOTE'

        feed_item.save()


def down(apps, schema_editor):
    return

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_remove_note_old_content_md'),
        ('feed', '0033_feeditem_post_type' ),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
