# Generated by Django 5.2.11 on 2026-04-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_auto_20260313_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
