# Generated by Django 5.2.13 on 2026-05-15 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, null=True)),
                ('issued_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.URLField()),
                ('token', models.TextField()),
                ('expires_utc', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, null=True)),
                ('issued_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.URLField()),
                ('code', models.CharField(max_length=45, unique=True)),
                ('redirect_uri', models.URLField()),
                ('code_challenge', models.CharField(max_length=255)),
                ('code_challenge_method', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, null=True)),
                ('issued_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.URLField()),
                ('token', models.TextField()),
                ('expires_utc', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
