# Generated by Django 5.2.13 on 2026-05-11 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='issued_utc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
