# Generated by Django 5.2.14 on 2026-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='code_challenge_method',
            field=models.CharField(choices=[('S256', 'S256')], max_length=10),
        ),
    ]
