# Generated by Django 5.2.13 on 2026-05-11 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0002_authcode_issued_utc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='code_challenge',
            field=models.CharField(default='code_challenge', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authcode',
            name='code_challenge_method',
            field=models.CharField(default='S256', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authcode',
            name='scope',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authcode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authcode',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('scope', models.CharField(max_length=255)),
                ('issued_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_utc', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
