# Generated by Django 5.2.13 on 2026-05-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0003_authcode_code_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='client_id',
            field=models.URLField(default='https://www.brentlineberry.com'),
            preserve_default=False,
        ),
    ]
