# Generated by Django 5.2.13 on 2026-05-14 14:20

import django.db.models.deletion
import django.utils.timezone
import indieauth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0004_accesstoken_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('scope', models.CharField(max_length=255)),
                ('client_id', models.URLField()),
                ('issued_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_utc', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, indieauth.models.IndieAuthBase),
        ),
    ]
