# Generated by Django 5.2.13 on 2026-05-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0005_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcode',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='authcode',
            name='issued_utc',
        ),
        migrations.RemoveField(
            model_name='authcode',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='authcode',
            name='user',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='revoked_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='revoked_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='scope',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='scope',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_utc', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Created from auth code', 'Created Auth'), ('Created from refresh token', 'Created Refresh'), ('Redeemed for profile URL', 'Redeemed Profile'), ('Redeemed for a token', 'Redeemed Token'), ('Revoked', 'Revoked'), ('User info requested', 'User Info')], max_length=26)),
                ('client_id', models.URLField()),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indieauth.accesstoken')),
                ('auth_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indieauth.authcode')),
                ('refresh_token', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indieauth.refreshtoken')),
            ],
        ),
    ]
