# Generated by Django 5.2.5 on 2025-08-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('webmentions', '0001_squashed_0011_alloweddomain_unique_domain'), ('webmentions', '0012_alter_alloweddomain_domain')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingWebmention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.URLField(help_text='The URL that mentions the target.')),
                ('target', models.URLField(help_text='The URL that is mentioned by the source.')),
                ('result', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('tries', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_source_url_per_target_url_outgoingwebmention')],
            },
        ),
        migrations.CreateModel(
            name='OutgoingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_url', models.URLField(help_text='The URL with links in the content.')),
                ('result', models.TextField(blank=True, default='')),
                ('tries', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_url',), name='unique_content_url')],
            },
        ),
        migrations.CreateModel(
            name='IncomingWebmention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.URLField(help_text='The URL that mentions the target.')),
                ('target', models.URLField(help_text='The URL that is mentioned by the source.')),
                ('tries', models.PositiveSmallIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('source_content', models.TextField(null=True)),
                ('source_content_type', models.CharField(max_length=50, null=True)),
                ('h_entry', models.JSONField(null=True)),
                ('h_card', models.JSONField(null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='unique_source_url_per_target_url_incomingwebmention')],
            },
        ),
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='The domain from which to auto-approve webmentions.', max_length=1000)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('domain',), name='unique_domain')],
            },
        ),
    ]
