# Generated by Django 4.2.3 on 2023-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebmention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.URLField(help_text='The URL that mentions the target.')),
                ('verified', models.BooleanField(default=False)),
                ('source_content', models.TextField(null=True)),
                ('source_content_type', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('MENTION', 'Mention'), ('REPLY', 'Reply'), ('LIKE', 'Like'), ('BOOKMARK', 'Bookmark'), ('REPOST', 'Repost')], default='MENTION', max_length=8)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingWebmention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.URLField(help_text='The URL that mentions the target.')),
                ('target', models.URLField(help_text='The URL that is mentioned by the source.')),
                ('result', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('tries', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PendingIncomingWebmention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.URLField(help_text='The URL that mentions the target.')),
                ('processed', models.BooleanField(default=False)),
                ('result', models.TextField(null=True)),
                ('target', models.URLField(help_text='The URL that is mentioned by the source.')),
                ('tries', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingOutgoingWebmention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.URLField(help_text='The URL that mentions the target.')),
                ('processed', models.BooleanField(default=False)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pendingoutgoingwebmention',
            constraint=models.UniqueConstraint(fields=('source',), name='unique_source_url'),
        ),
        migrations.AddConstraint(
            model_name='pendingincomingwebmention',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_source_url_per_target_url'),
        ),
        migrations.AddConstraint(
            model_name='outgoingwebmention',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_source_url_per_target_url_outgoingwebmention'),
        ),
    ]
