# Generated by Django 4.2.3 on 2023-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingwebmention',
            name='target',
            field=models.URLField(default='http://orangegnome.com', help_text='The URL that is mentioned by the source.'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='incomingwebmention',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_source_url_per_target_url_incomingwebmention'),
        ),
    ]
