# Generated by Django 4.2.3 on 2023-08-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0003_incomingwebmention_h_card_incomingwebmention_h_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webmentionable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
