# Generated by Django 4.2.3 on 2023-08-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0004_alter_incomingwebmention_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingwebmention',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
