# Generated by Django 4.2.3 on 2023-08-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0004_webmentionable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webmentionable',
        ),
    ]
