# Generated by Django 4.2.3 on 2023-08-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0005_incomingwebmention_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingwebmention',
            options={},
        ),
    ]
