# Generated by Django 4.2.3 on 2023-08-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webmentions', '0005_delete_webmentionable'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingwebmention',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='incomingwebmention',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
