# Generated by Django 4.2.3 on 2023-08-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0006_incomingwebmention_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingwebmention',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='incomingwebmention',
            name='object_id',
        ),
    ]
