# Generated by Django 4.2.3 on 2023-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0007_remove_incomingwebmention_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
