# Generated by Django 4.2.3 on 2023-08-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0008_alloweddomains'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllowedDomains',
            new_name='AllowedDomain',
        ),
    ]
