# Generated by Django 4.2.3 on 2023-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0008_incomingwebmention_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingwebmention',
            name='h_card',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomingwebmention',
            name='h_entry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
