# Generated by Django 4.2.3 on 2023-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0009_rename_alloweddomains_alloweddomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddomain',
            name='domain',
            field=models.CharField(default='', help_text='The domain from which to auto-approve webmentions.', max_length=1000),
            preserve_default=False,
        ),
    ]
