# Generated by Django 4.2.3 on 2023-08-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmentions', '0010_alloweddomain_domain'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alloweddomain',
            constraint=models.UniqueConstraint(fields=('domain',), name='unique_domain'),
        ),
    ]
