# Generated by Django 5.2.5 on 2025-08-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('feed', '0001_squashed_0003_feeditem_tags'), ('feed', '0004_auto_20200417_2246_squashed_0009_alter_feeditem_published'), ('feed', '0010_syndication'), ('feed', '0011_alter_feeditem_updated'), ('feed', '0012_feeditem_created')]

    initial = True

    dependencies = [
        ('profiles', '0001_squashed_0002_profile_twitter_screenname'),
        ('syndications', '0001_squashed_0016_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(blank=True, related_name='feed_items', to='feed.tag')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syndication',
            fields=[
                ('syndication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syndications.syndication')),
                ('syndicated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syndications', to='feed.feeditem')),
            ],
            bases=('syndications.syndication',),
        ),
    ]
