# Generated by Django 5.2.13 on 2026-04-30 20:47

import django.db.models.deletion
import feed.models
import feed.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('feed', '0001_squashed_0012_feeditem_created'), ('feed', '0013_feeditem_new_syndicate_to_mastodon_and_more'), ('feed', '0014_feeditem_syndicate_to_mastodon_and_more'), ('feed', '0015_auto_20251228_1200'), ('feed', '0016_remove_feeditem_new_syndicate_to_mastodon_and_more'), ('feed', '0017_feeditem_new_content_md'), ('feed', '0018_rename_new_content_md_feeditem_content_md'), ('feed', '0019_feeditem_new_summary_md'), ('feed', '0020_rename_new_summary_md_feeditem_summary_md'), ('feed', '0021_feeditem_new_quote_md'), ('feed', '0022_rename_new_quote_md_feeditem_quote_md'), ('feed', '0023_feeditem_new_title_md'), ('feed', '0024_rename_new_title_md_feeditem_title_md'), ('feed', '0025_feeditem_new_url'), ('feed', '0026_rename_new_url_feeditem_url'), ('feed', '0027_image_postimage_feeditem_images'), ('feed', '0028_alter_postimage_order'), ('feed', '0029_feeditem_new_source_author_name_and_more'), ('feed', '0030_rename_new_source_author_name_feeditem_source_author_name_and_more'), ('feed', '0031_feeditem_new_slug'), ('feed', '0032_rename_new_slug_feeditem_slug'), ('feed', '0033_feeditem_post_type'), ('feed', '0034_article_bookmark_like_note_photo_repost'), ('feed', '0035_alter_feeditem_content_md_alter_feeditem_post_type_and_more')]

    initial = True

    dependencies = [
        ('profiles', '0001_squashed_0004_remove_profile_twitter_screenname'),
        ('syndications', '0001_squashed_0018_delete_tweet_delete_twitteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(blank=True, related_name='feed_items', to='feed.tag')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('syndicate_to_mastodon', models.BooleanField(default=False)),
                ('syndicated_to_mastodon', models.DateTimeField(null=True)),
                ('content_md', models.TextField(blank=True, help_text='Markdown supported.', null=True)),
                ('summary_md', models.TextField(blank=True, help_text='Markdown supported.', null=True)),
                ('quote_md', models.TextField(blank=True, help_text='CommonMark supported.', verbose_name='quote')),
                ('title_md', models.TextField(blank=True, help_text='Markdown supported. Inline elements only.', verbose_name='title')),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syndication',
            fields=[
                ('syndication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syndications.syndication')),
                ('syndicated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syndications', to='feed.feeditem')),
            ],
            bases=('syndications.syndication',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', feed.models.OGResizedImageField(crop=None, force_format=None, height_field='image_height', keep_meta=False, quality=70, scale=None, size=[1188, 1188], storage=feed.storage.PublicAzureStorage, upload_to=feed.models.upload_to_callable, width_field='image_width')),
                ('image_height', models.PositiveIntegerField()),
                ('image_width', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('feature', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feeditem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='feeditem',
            name='images',
            field=models.ManyToManyField(related_name='posts', through='feed.PostImage', to='feed.image'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='source_author_name',
            field=models.CharField(blank=True, default='Anonymous', help_text='Used for Reposts.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='source_author_url',
            field=models.URLField(blank=True, help_text='Used for Reposts.', null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='source_name',
            field=models.CharField(blank=True, help_text='Used for Reposts.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for Articles.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='post_type',
            field=models.CharField(blank=True, choices=[('ARTICLE', 'Article'), ('BOOKMARK', 'Bookmark'), ('LIKE', 'Like'), ('NOTE', 'Note'), ('PHOTO', 'Photo'), ('REPOST', 'Repost')], max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='content_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Used for Notes, Articles, Bookmarks, Photos, and Reposts.', null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='quote_md',
            field=models.TextField(blank=True, help_text='CommonMark supported. Used for Bookmarks.', verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='summary_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Used for Articles.', null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='title_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Inline elements only. Used for Articles and Bookmarks.', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.URLField(blank=True, help_text='Used for Bookmarks, Likes, and Reposts.', max_length=2048, null=True),
        ),
    ]
