# Generated by Django 4.2.18 on 2025-02-07 13:59

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# feed.migrations.0005_auto_20200417_2353

class Migration(migrations.Migration):

    replaces = [('feed', '0004_auto_20200417_2246'), ('feed', '0005_auto_20200417_2353'), ('feed', '0006_auto_20200423_1653'), ('feed', '0007_feeditem_in_reply_to'), ('feed', '0008_remove_feeditem_is_published'), ('feed', '0009_alter_feeditem_published')]

    dependencies = [
        ('feed', '0001_squashed_0003_feeditem_tags'),
        ('profiles', '0001_squashed_0002_profile_twitter_screenname'),
        ('posts', '0029_auto_20200417_2244'),
        ('notes', '0012_auto_20200417_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='feed_items', to='feed.tag'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
