# Generated by Django 3.0.4 on 2020-04-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_twitter_screenname'),
        ('feed', '0003_feeditem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
