# Generated by Django 3.0.4 on 2020-04-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200417_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='feed_items', to='feed.Tag'),
        ),
    ]
