# Generated by Django 3.0.4 on 2020-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200423_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
