# Generated by Django 4.2.3 on 2023-07-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_feeditem_in_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='is_published',
        ),
    ]
