# Generated by Django 4.2.18 on 2025-01-27 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syndications', '0015_syndication_mastodonstatus_syndication_and_more'),
        ('feed', '0009_alter_feeditem_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syndication',
            fields=[
                ('syndication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='syndications.syndication')),
                ('syndicated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syndications', to='feed.feeditem')),
            ],
            bases=('syndications.syndication',),
        ),
    ]
