# Generated by Django 4.2.18 on 2025-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_feeditem_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
