# Generated by Django 5.2.5 on 2025-08-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_squashed_0012_feeditem_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_syndicate_to_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='new_syndicated_to_mastodon',
            field=models.DateTimeField(null=True),
        ),
    ]
