# Generated by Django 5.2.5 on 2025-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_feeditem_new_syndicate_to_mastodon_and_more'),
        ('bookmarks', '0014_remove_bookmark_syndicate_to_mastodon_and_more'),
        ('likes', '0004_remove_like_syndicate_to_mastodon_and_more'),
        ('notes', '0023_remove_note_syndicate_to_mastodon_and_more'),
        ('photos', '0014_remove_photo_syndicate_to_mastodon_and_more'),
        ('posts', '0039_remove_post_syndicate_to_mastodon_and_more'),
        ('reposts', '0006_remove_repost_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='syndicate_to_mastodon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='syndicated_to_mastodon',
            field=models.DateTimeField(null=True),
        ),
    ]
