# Generated by Django 5.2.5 on 2025-12-28 17:00

from django.db import migrations

def up(apps, schema_editor):
    app_label = "feed"
    model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)

    for item in model.objects.all():
        item.syndicate_to_mastodon = item.new_syndicate_to_mastodon
        item.syndicated_to_mastodon = item.new_syndicated_to_mastodon

        item.save()


def down(apps, schema_editor):
    app_label = "feed"
    model_str = "FeedItem"

    model = apps.get_model(app_label, model_str)

    for item in model.objects.all():
        item.new_syndicate_to_mastodon = item.syndicate_to_mastodon
        item.new_syndicated_to_mastodon = item.syndicated_to_mastodon

        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_feeditem_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
