# Generated by Django 5.2.5 on 2025-12-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20251228_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeditem',
            name='new_syndicate_to_mastodon',
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='new_syndicated_to_mastodon',
        ),
    ]
