# Generated by Django 5.2.5 on 2026-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_remove_feeditem_new_syndicate_to_mastodon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_content_md',
            field=models.TextField(blank=True, help_text='Markdown supported.', null=True),
        ),
    ]
