# Generated by Django 5.2.5 on 2026-01-11 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_feeditem_new_content_md'),
        ('notes', '0025_rename_content_md_note_old_content_md'),
        ('posts', '0041_rename_content_md_post_old_content_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_content_md',
            new_name='content_md',
        ),
    ]
