# Generated by Django 5.2.11 on 2026-02-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_rename_new_content_md_feeditem_content_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_summary_md',
            field=models.TextField(blank=True, help_text='Markdown supported.', null=True),
        ),
    ]
