# Generated by Django 5.2.11 on 2026-02-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_feeditem_new_summary_md'),
        ('posts', '0044_rename_summary_md_post_old_summary_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_summary_md',
            new_name='summary_md',
        ),
    ]
