# Generated by Django 5.2.11 on 2026-02-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_rename_new_summary_md_feeditem_summary_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_quote_md',
            field=models.TextField(blank=True, help_text='CommonMark supported.', verbose_name='quote'),
        ),
    ]
