# Generated by Django 5.2.11 on 2026-02-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_feeditem_new_quote_md'),
        ('bookmarks', '0018_rename_quote_md_bookmark_old_quote_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_quote_md',
            new_name='quote_md',
        ),
    ]
