# Generated by Django 5.2.11 on 2026-02-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_rename_new_quote_md_feeditem_quote_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_title_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Inline elements only.', verbose_name='title'),
        ),
    ]
