# Generated by Django 5.2.11 on 2026-02-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_feeditem_new_title_md'),
        ('bookmarks', '0021_rename_title_md_bookmark_old_title_md'),
        ('posts', '0047_rename_title_md_post_old_title_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_title_md',
            new_name='title_md',
        ),
    ]
