# Generated by Django 5.2.11 on 2026-02-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_rename_new_title_md_feeditem_title_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
