# Generated by Django 5.2.11 on 2026-02-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0025_feeditem_new_url'),
        ('bookmarks', '0025_rename_url_bookmark_old_url'),
        ('likes', '0007_rename_url_like_old_url'),
        ('reposts', '0009_rename_url_repost_old_url')
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_url',
            new_name='url',
        ),
    ]
