# Generated by Django 5.2.11 on 2026-02-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0025_feeditem_new_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_url',
            new_name='url',
        ),
    ]
