# Generated by Django 5.2.11 on 2026-03-06 01:38

import django.db.models.deletion
import feed.models
import feed.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0026_rename_new_url_feeditem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', feed.models.OGResizedImageField(crop=None, force_format=None, height_field='image_height', keep_meta=False, quality=70, scale=None, size=[1188, 1188], storage=feed.storage.PublicAzureStorage, upload_to=feed.models.upload_to_callable, width_field='image_width')),
                ('image_height', models.PositiveIntegerField()),
                ('image_width', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('feature', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feeditem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='feeditem',
            name='images',
            field=models.ManyToManyField(related_name='posts', through='feed.PostImage', to='feed.image'),
        ),
    ]
