# Generated by Django 5.2.11 on 2026-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0027_image_postimage_feeditem_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
    ]
