# Generated by Django 5.2.11 on 2026-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0028_alter_postimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_source_author_name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='new_source_author_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='new_source_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
