# Generated by Django 5.2.11 on 2026-03-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0029_feeditem_new_source_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_source_author_name',
            new_name='source_author_name',
        ),
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_source_author_url',
            new_name='source_author_url',
        ),
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_source_name',
            new_name='source_name',
        ),
    ]
