# Generated by Django 5.2.11 on 2026-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0030_rename_new_source_author_name_feeditem_source_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='new_slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
