# Generated by Django 5.2.11 on 2026-03-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0031_feeditem_new_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='new_slug',
            new_name='slug',
        ),
    ]
