# Generated by Django 5.2.11 on 2026-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0032_rename_new_slug_feeditem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='post_type',
            field=models.CharField(blank=True, choices=[('BOOKMARK', 'Bookmark'), ('LIKE', 'Like'), ('NOTE', 'Note'), ('PHOTO', 'Photo'), ('ARTICLE', 'Article'), ('REPOST', 'Repost')], max_length=8, null=True),
        ),
    ]
