# Generated by Django 5.2.11 on 2026-04-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0033_feeditem_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.feeditem',),
        ),
    ]
