# Generated by Django 5.2.11 on 2026-04-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0034_article_bookmark_like_note_photo_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='content_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Used for Notes, Articles, Bookmarks, Photos, and Reposts.', null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='post_type',
            field=models.CharField(blank=True, choices=[('ARTICLE', 'Article'), ('BOOKMARK', 'Bookmark'), ('LIKE', 'Like'), ('NOTE', 'Note'), ('PHOTO', 'Photo'), ('REPOST', 'Repost')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='quote_md',
            field=models.TextField(blank=True, help_text='CommonMark supported. Used for Bookmarks.', verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for Articles.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='source_author_name',
            field=models.CharField(blank=True, default='Anonymous', help_text='Used for Reposts.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='source_author_url',
            field=models.URLField(blank=True, help_text='Used for Reposts.', null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='source_name',
            field=models.CharField(blank=True, help_text='Used for Reposts.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='summary_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Used for Articles.', null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='title_md',
            field=models.TextField(blank=True, help_text='Markdown supported. Inline elements only. Used for Articles and Bookmarks.', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='url',
            field=models.URLField(blank=True, help_text='Used for Bookmarks, Likes, and Reposts.', max_length=2048, null=True),
        ),
    ]
