# Generated by Django 5.2.13 on 2026-05-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_squashed_0035_alter_feeditem_content_md_alter_feeditem_post_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='feature',
            new_name='featured',
        ),
    ]
