# Generated by Django 5.2.13 on 2026-05-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0036_rename_feature_postimage_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['-featured', 'order']},
        ),
    ]
