# Generated by Django 5.2.14 on 2026-05-19 15:26

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0037_alter_postimage_options'),
        ('profiles', '0005_metatag'),
    ]

    operations = [
        migrations.DeleteModel('Article'),
        migrations.DeleteModel('Bookmark'),
        migrations.DeleteModel('Like'),
        migrations.DeleteModel('Note'),
        migrations.DeleteModel('Photo'),
        migrations.DeleteModel('Repost'),
        migrations.RenameModel(
            old_name='FeedItem',
            new_name='Post',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.post',),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.post',),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.post',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.post',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.post',),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feed.post',),
        ),
    ]
