# Generated by Django 5.2.14 on 2026-06-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0038_rename_feeditem_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
