# Generated by Django 5.2.14 on 2026-06-11 20:34

from django.db import migrations

def up(apps, schema_editor):
    app_label = "feed"
    model_str = "Image"

    model = apps.get_model(app_label, model_str)

    for item in model.objects.all():
        if not item.posts.exists():
            continue

        first_created = item.posts.order_by("created").first()
        last_updated = item.posts.order_by("-updated").first()

        item.created = first_created.created
        item.updated = last_updated.updated
        
        item.save()

def down(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0039_image_created_image_updated'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
