# Generated by Django 5.2.14 on 2026-06-11 20:34

from django.db import migrations

def up(apps, schema_editor):
    app_label = "feed"
    model_str = "Image"

    model = apps.get_model(app_label, model_str)

    for item in model.objects.all():
        if not item.posts.exists():
            continue

        first_created = item.posts.order_by("created").first()
        first_published = item.posts.order_by("published").first()
        last_updated = item.posts.order_by("-updated").first()

        dates = [first_created.created, first_published.published, last_updated.updated]

        created = min(d for d in dates if d is not None)
        updated = max(d for d in dates if d is not None)
        
        item.created = created
        item.updated = updated
        
        item.save()

def down(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0039_image_created_image_updated'),
    ]

    operations = [
        migrations.RunPython(up,down)
    ]
