# Generated by Django 5.2.14 on 2026-06-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0040_auto_20260611_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
