# Generated by Django 4.2.18 on 2025-02-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syndications', '0001_squashed_0016_data_migration'),
        ('feed', '0001_squashed_0012_feeditem_created'),
        ('profiles', '0001_squashed_0004_remove_profile_twitter_screenname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('feeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feeditem')),
                ('type', models.CharField(max_length=30)),
                ('distance', models.FloatField()),
                ('moving_time', models.IntegerField()),
                ('total_elevation_gain', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('start_date_local', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('comments', models.TextField(null=True)),
            ],
            bases=('feed.feeditem',),
        ),
    ]
