# Generated by Django 3.0.4 on 2020-05-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='strava_activity',
        ),
    ]
