# Generated by Django 5.2.11 on 2026-04-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_squashed_0003_remove_exercise_strava_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
